// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBContext.CURD_Product;

public partial class ProductCategory
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int? Status { get; set; }

    public DateTime? CreateTime { get; set; }

    public string Keyword { get; set; }

    public int? CreateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual Account CreateByNavigation { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}