// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUD_Product.Models;

public partial class MediaFile
{
    public int Id { get; set; }

    public string OriginalName { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public double? FileSize { get; set; }

    public DateTime? UploadDate { get; set; }

    public string MimeType { get; set; }

    public int? UploadedBy { get; set; }

    public string FileCode { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual Account UploadedByNavigation { get; set; }
}