// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUD_Product.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string Content { get; set; }

    public string Keywords { get; set; }

    public decimal Price { get; set; }

    public int Quantity { get; set; }

    public int? Status { get; set; }

    public DateTime? CreateTime { get; set; }

    public int ProductCategoryId { get; set; }

    public int? CreateBy { get; set; }

    public int? UpdateBy { get; set; }

    public int? MediaId { get; set; }

    public virtual Account CreateByNavigation { get; set; }

    public virtual MediaFile Media { get; set; }

    public virtual ProductCategory ProductCategory { get; set; }
}